insert into races (id, name, date, city, state, race_type) values (1, 'BRAC Cross Cup Awards Party', '2016-01-30', 'Westminster', 'CO', 'OTHER')
insert into races (id, name, date, city, state, race_type) values (2, 'BRAC Officials Meeting', '2016-02-20', 'USA Cycling Office - CO Spgs (2:30)', 'CO', 'OTHER')
insert into races (id, name, date, city, state, race_type) values (3, 'CX Race Directors Meeting', '2016-02-24', 'Littleton', 'CO', 'OTHER')
insert into races (id, name, date, city, state, race_type) values (4, 'Frostbite Time Trial', '2016-03-05', 'FortCollins', 'CO', 'TIME_TRIAL')
insert into races (id, name, date, city, state, race_type) values (5, 'University of Denver Criterium', '2016-03-06', 'Denver', 'CO', 'CRITERIUM')
insert into races (id, name, date, city, state, race_type) values (6, 'Oredigger Classic- Lookout Mtn TT', '2016-03-19', 'Golden', 'CO', 'TIME_TRIAL')
insert into races (id, name, date, city, state, race_type) values (7, 'Oredigger Classic- Criterium', '2016-03-20', 'Golden', 'CO', 'CRITERIUM')
insert into races (id, name, date, city, state, race_type) values (8, 'Front Range Classic - USAFA Criterium', '2016-04-02', 'USAFA', 'CO', 'CRITERIUM')
insert into races (id, name, date, city, state, race_type) values (9, 'Louisville Criterium', '2016-04-02', 'Louisville', 'CO', 'CRITERIUM')
insert into races (id, name, date, city, state, race_type) values (10, 'Front Range Classic - USAFA Road Race', '2016-04-03', 'USAFA', 'CO', 'ROAD_RACE')
insert into races (id, name, date, city, state, race_type) values (11, 'Karen Hornbostel Meml TT #1 @ Cherry Creek State Park', '2016-04-06', 'Denver', 'CO', 'TIME_TRIAL')
insert into races (id, name, date, city, state, race_type) values (12, 'Buffs Gold TT/TTT', '2016-04-09', 'Boulder', 'CO', 'TIME_TRIAL')
insert into races (id, name, date, city, state, race_type) values (13, 'Buffs Gold Circuit Race', '2016-04-10', 'Boulder', 'CO', 'ROAD_RACE')
insert into races (id, name, date, city, state, race_type) values (14, 'Karen Hornbostel Meml TT #2 @ Cherry Creek State Park', '2016-04-13', 'Denver', 'CO', 'TIME_TRIAL')
insert into races (id, name, date, city, state, race_type) values (15, 'CSU Rams Circuit Race', '2016-04-16', 'Fort Collins', 'CO', 'ROAD_RACE')
insert into races (id, name, date, city, state, race_type) values (16, 'CSU Oval Criterium', '2016-04-17', 'Fort Collins', 'CO', 'CRITERIUM')
insert into races (id, name, date, city, state, race_type) values (17, 'Karen Hornbostel Meml TT #3 @ Cherry Creek State Park', '2016-04-20', 'Denver', 'CO', 'TIME_TRIAL')
insert into races (id, name, date, city, state, race_type) values (18, 'Clasica de Rio Grande', '2016-04-23', 'Johnstown', 'CO', 'OTHER')
insert into races (id, name, date, city, state, race_type) values (19, 'FLC Squawker Classic- TTT', '2016-04-23', 'Durango', 'CO', 'TIME_TRIAL')
insert into races (id, name, date, city, state, race_type) values (20, 'FLC Squawker Classic- Criterium', '2016-04-23', 'Durango', 'CO', 'CRITERIUM')
insert into races (id, name, date, city, state, race_type) values (21, 'FLC Squawker Classic- Road Race', '2016-04-24', 'Durango', 'CO', 'ROAD_RACE')
insert into races (id, name, date, city, state, race_type) values (22, 'Denver Federal Center Classic', '2016-04-24', 'Lakewood', 'CO', 'OTHER')
insert into races (id, name, date, city, state, race_type) values (23, 'Karen Hornbostel Meml TT #4 @ Cherry Creek State Park', '2016-04-27', 'Denver', 'CO', 'TIME_TRIAL')
insert into races (id, name, date, city, state, race_type) values (24, 'Maverick Classic', '2016-04-29', 'Grand Junction', 'CO', 'OTHER')
insert into races (id, name, date, city, state, race_type) values (25, 'Maverick Classic', '2016-04-30', 'Grand Junction', 'CO', 'OTHER')
insert into races (id, name, date, city, state, race_type) values (26, 'Maverick Classic', '2016-05-01', 'Grand Junction', 'CO', 'OTHER')
insert into races (id, name, date, city, state, race_type) values (27, 'Koppenberg', '2016-05-01', 'Superior', 'CO', 'OTHER')
insert into races (id, name, date, city, state, race_type) values (28, 'Karen Hornbostel Meml TT #5 @ Cherry Creek State Park', '2016-05-04', 'Denver', 'CO', 'TIME_TRIAL')
insert into races (id, name, date, city, state, race_type) values (29, '0Z Road Race', '2016-05-07', 'Watkins', 'CO', 'ROAD_RACE')
insert into races (id, name, date, city, state, race_type) values (30, 'Karen Hornbostel Meml TT #6 @ Cherry Creek State Park', '2016-05-11', 'Denver', 'CO', 'TIME_TRIAL')
insert into races (id, name, date, city, state, race_type) values (31, 'Best on Hess Individual Time Trial', '2016-05-14', 'Castle Pines', 'CO', 'TIME_TRIAL')
insert into races (id, name, date, city, state, race_type) values (32, 'Karen Hornbostel Meml TT #7 @ Cherry Creek State Park', '2016-05-18', 'Denver', 'CO', 'TIME_TRIAL')
insert into races (id, name, date, city, state, race_type) values (33, 'Superior Morgul Classic- TT', '2016-05-20', 'Louisville', 'CO', 'TIME_TRIAL')
insert into races (id, name, date, city, state, race_type) values (34, 'Superior Morgul Classic- RR', '2016-05-21', 'Louisville', 'CO', 'ROAD_RACE')
insert into races (id, name, date, city, state, race_type) values (35, 'Superior Morgul Classic- RR', '2016-05-22', 'Louisville', 'CO', 'ROAD_RACE')
insert into races (id, name, date, city, state, race_type) values (36, 'City Park Criterium', '2016-06-04', 'Denver', 'CO', 'CRITERIUM')
insert into races (id, name, date, city, state, race_type) values (37, 'Deer Trail RR - CO Senior RR Championships', '2016-06-05', 'Deer Trail', 'CO', 'ROAD_RACE')
insert into races (id, name, date, city, state, race_type) values (38, 'Guanella Pass Hill Climb', '2016-06-11', 'Georgetown', '', 'HILL_CLIMB')
insert into races (id, name, date, city, state, race_type) values (39, 'Ridge at 38 Criterium - CO Senior Crit Championships', '2016-06-12', 'Wheat Ridge', 'CO', 'CRITERIUM')
insert into races (id, name, date, city, state, race_type) values (40, 'Parker 3-Day: TT', '2016-06-17', 'Parker', 'CO', 'TIME_TRIAL')
insert into races (id, name, date, city, state, race_type) values (41, 'Parker 3-Day: Crit', '2016-06-18', 'Parker', 'CO', 'CRITERIUM')
insert into races (id, name, date, city, state, race_type) values (42, 'Parker 3-Day: RR', '2016-06-19', 'Parker', 'CO', 'ROAD_RACE')
insert into races (id, name, date, city, state, race_type) values (43, 'Boulder Stage Race - TT', '2016-06-24', 'Boulder', 'CO', 'TIME_TRIAL')
insert into races (id, name, date, city, state, race_type) values (44, 'Boulder Stage Race - Circuit Race', '2016-06-25', 'Boulder', 'CO', 'ROAD_RACE')
insert into races (id, name, date, city, state, race_type) values (45, 'Boulder Stage Race - Hill Climb', '2016-06-26', 'Boulder', 'CO', 'HILL_CLIMB')
insert into races (id, name, date, city, state, race_type) values (46, 'Boulder Stage Race- GC', '2016-06-26', 'Boulder', 'CO', 'OTHER')
insert into races (id, name, date, city, state, race_type) values (47, 'Boulder Orthopedics Crit @ Table Mountain', '2016-07-02', 'Golden', 'CO', 'CRITERIUM')
insert into races (id, name, date, city, state, race_type) values (48, 'Sunshine HillClimb', '2016-07-09', 'Boulder', 'CO', 'HILL_CLIMB')
insert into races (id, name, date, city, state, race_type) values (49, '30th Annual Longmont Criterium', '2016-07-10', 'Longmont', 'CO', 'CRITERIUM')
insert into races (id, name, date, city, state, race_type) values (50, 'Salida Classic -TT', '2016-07-15', 'Salida', 'CO', 'TIME_TRIAL')
insert into races (id, name, date, city, state, race_type) values (51, 'Salida Classic - Criterium', '2016-07-16', 'Salida', 'CO', 'CRITERIUM')
insert into races (id, name, date, city, state, race_type) values (52, 'Salida Classic Road Race - CO Master RR Championships', '2016-07-17', 'Salida', 'CO', 'ROAD_RACE')
insert into races (id, name, date, city, state, race_type) values (53, 'Bob Cook Meml Mt Evans HC- CO HC Championships', '2016-07-23', 'Idaho Springs', 'CO', 'HILL_CLIMB')
insert into races (id, name, date, city, state, race_type) values (54, 'Mike Nields Meml Bannock St Crit - CO Jr Crit Championships', '2016-07-31', 'Denver', 'CO', 'CRITERIUM')
insert into races (id, name, date, city, state, race_type) values (55, 'Littleton Twilight Criterium', '2016-08-06', 'Littleton', 'CO', 'CRITERIUM')
insert into races (id, name, date, city, state, race_type) values (56, 'John Stenner Meml - CO Time Trial Championships', '2016-08-07', 'TBD', 'CO', 'TIME_TRIAL')
insert into races (id, name, date, city, state, race_type) values (57, 'Belleview Dental Classic', '2016-08-14', 'TBD', 'CO', 'OTHER')
insert into races (id, name, date, city, state, race_type) values (58, 'Lucky Pie Criterium -  CO Master Crit Championships', '2016-08-21', 'Louisville', 'CO', 'CRITERIUM')
insert into races (id, name, date, city, state, race_type) values (59, 'CBL Lookout Mountain HC', '2016-08-27', 'Golden', 'CO', 'HILL_CLIMB')
insert into races (id, name, date, city, state, race_type) values (60, 'Lafayette Criterium', '2016-08-28', 'Lafayette', 'CO', 'CRITERIUM')
insert into races (id, name, date, city, state, race_type) values (61, 'Steamboat Springs Stage Race - Circuit Race (SMP 1-2 SM 3 SW P-1-2)', '2016-09-02', 'Steamboat Springs', 'CO', 'ROAD_RACE')
insert into races (id, name, date, city, state, race_type) values (62, 'Steamboat Springs Stage Race - TT', '2016-09-03', 'Steamboat Springs', 'CO', 'TIME_TRIAL')
insert into races (id, name, date, city, state, race_type) values (63, 'Steamboat Springs Stage Race - RR', '2016-09-04', 'Steamboat Springs', 'CO', 'ROAD_RACE')
insert into races (id, name, date, city, state, race_type) values (64, 'Steamboat Springs Stage Race - GC', '2016-09-05', 'Steamboat Springs', 'CO', 'OTHER')
insert into races (id, name, date, city, state, race_type) values (65, 'Steamboat Springs Stage Race - Crit', '2016-09-05', 'Steamboat Springs', 'CO', 'CRITERIUM')