// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: racedirectory.proto

package belllap.proto;

public final class RaceDirectoryProto {
  private RaceDirectoryProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RaceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.Race)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>required string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>required string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional int64 date = 3;</code>
     */
    boolean hasDate();
    /**
     * <code>optional int64 date = 3;</code>
     */
    long getDate();

    /**
     * <code>optional string city = 4;</code>
     */
    boolean hasCity();
    /**
     * <code>optional string city = 4;</code>
     */
    java.lang.String getCity();
    /**
     * <code>optional string city = 4;</code>
     */
    com.google.protobuf.ByteString
        getCityBytes();

    /**
     * <code>optional string state = 5;</code>
     */
    boolean hasState();
    /**
     * <code>optional string state = 5;</code>
     */
    java.lang.String getState();
    /**
     * <code>optional string state = 5;</code>
     */
    com.google.protobuf.ByteString
        getStateBytes();

    /**
     * <code>optional .proto.Race.RaceType raceType = 6;</code>
     */
    boolean hasRaceType();
    /**
     * <code>optional .proto.Race.RaceType raceType = 6;</code>
     */
    belllap.proto.RaceDirectoryProto.Race.RaceType getRaceType();
  }
  /**
   * Protobuf type {@code proto.Race}
   */
  public static final class Race extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:proto.Race)
      RaceOrBuilder {
    // Use Race.newBuilder() to construct.
    private Race(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Race(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Race defaultInstance;
    public static Race getDefaultInstance() {
      return defaultInstance;
    }

    public Race getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Race(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              id_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              name_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              date_ = input.readInt64();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              city_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              state_ = bs;
              break;
            }
            case 48: {
              int rawValue = input.readEnum();
              belllap.proto.RaceDirectoryProto.Race.RaceType value = belllap.proto.RaceDirectoryProto.Race.RaceType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(6, rawValue);
              } else {
                bitField0_ |= 0x00000020;
                raceType_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return belllap.proto.RaceDirectoryProto.internal_static_proto_Race_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return belllap.proto.RaceDirectoryProto.internal_static_proto_Race_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              belllap.proto.RaceDirectoryProto.Race.class, belllap.proto.RaceDirectoryProto.Race.Builder.class);
    }

    public static com.google.protobuf.Parser<Race> PARSER =
        new com.google.protobuf.AbstractParser<Race>() {
      public Race parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Race(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Race> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code proto.Race.RaceType}
     */
    public enum RaceType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>CRITERIUM = 0;</code>
       */
      CRITERIUM(0, 0),
      /**
       * <code>ROAD_RACE = 1;</code>
       */
      ROAD_RACE(1, 1),
      /**
       * <code>HILL_CLIMB = 2;</code>
       */
      HILL_CLIMB(2, 2),
      /**
       * <code>TIME_TRIAL = 3;</code>
       */
      TIME_TRIAL(3, 3),
      /**
       * <code>OTHER = 4;</code>
       */
      OTHER(4, 4),
      ;

      /**
       * <code>CRITERIUM = 0;</code>
       */
      public static final int CRITERIUM_VALUE = 0;
      /**
       * <code>ROAD_RACE = 1;</code>
       */
      public static final int ROAD_RACE_VALUE = 1;
      /**
       * <code>HILL_CLIMB = 2;</code>
       */
      public static final int HILL_CLIMB_VALUE = 2;
      /**
       * <code>TIME_TRIAL = 3;</code>
       */
      public static final int TIME_TRIAL_VALUE = 3;
      /**
       * <code>OTHER = 4;</code>
       */
      public static final int OTHER_VALUE = 4;


      public final int getNumber() { return value; }

      public static RaceType valueOf(int value) {
        switch (value) {
          case 0: return CRITERIUM;
          case 1: return ROAD_RACE;
          case 2: return HILL_CLIMB;
          case 3: return TIME_TRIAL;
          case 4: return OTHER;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<RaceType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<RaceType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<RaceType>() {
              public RaceType findValueByNumber(int number) {
                return RaceType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return belllap.proto.RaceDirectoryProto.Race.getDescriptor().getEnumTypes().get(0);
      }

      private static final RaceType[] VALUES = values();

      public static RaceType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private RaceType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:proto.Race.RaceType)
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    /**
     * <code>required string id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    /**
     * <code>required string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATE_FIELD_NUMBER = 3;
    private long date_;
    /**
     * <code>optional int64 date = 3;</code>
     */
    public boolean hasDate() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 date = 3;</code>
     */
    public long getDate() {
      return date_;
    }

    public static final int CITY_FIELD_NUMBER = 4;
    private java.lang.Object city_;
    /**
     * <code>optional string city = 4;</code>
     */
    public boolean hasCity() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string city = 4;</code>
     */
    public java.lang.String getCity() {
      java.lang.Object ref = city_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          city_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string city = 4;</code>
     */
    public com.google.protobuf.ByteString
        getCityBytes() {
      java.lang.Object ref = city_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        city_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATE_FIELD_NUMBER = 5;
    private java.lang.Object state_;
    /**
     * <code>optional string state = 5;</code>
     */
    public boolean hasState() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string state = 5;</code>
     */
    public java.lang.String getState() {
      java.lang.Object ref = state_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          state_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string state = 5;</code>
     */
    public com.google.protobuf.ByteString
        getStateBytes() {
      java.lang.Object ref = state_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        state_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RACETYPE_FIELD_NUMBER = 6;
    private belllap.proto.RaceDirectoryProto.Race.RaceType raceType_;
    /**
     * <code>optional .proto.Race.RaceType raceType = 6;</code>
     */
    public boolean hasRaceType() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional .proto.Race.RaceType raceType = 6;</code>
     */
    public belllap.proto.RaceDirectoryProto.Race.RaceType getRaceType() {
      return raceType_;
    }

    private void initFields() {
      id_ = "";
      name_ = "";
      date_ = 0L;
      city_ = "";
      state_ = "";
      raceType_ = belllap.proto.RaceDirectoryProto.Race.RaceType.CRITERIUM;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, date_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getCityBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getStateBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeEnum(6, raceType_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, date_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getCityBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getStateBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, raceType_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static belllap.proto.RaceDirectoryProto.Race parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static belllap.proto.RaceDirectoryProto.Race parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static belllap.proto.RaceDirectoryProto.Race parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static belllap.proto.RaceDirectoryProto.Race parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static belllap.proto.RaceDirectoryProto.Race parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static belllap.proto.RaceDirectoryProto.Race parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static belllap.proto.RaceDirectoryProto.Race parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static belllap.proto.RaceDirectoryProto.Race parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static belllap.proto.RaceDirectoryProto.Race parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static belllap.proto.RaceDirectoryProto.Race parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(belllap.proto.RaceDirectoryProto.Race prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.Race}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.Race)
        belllap.proto.RaceDirectoryProto.RaceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return belllap.proto.RaceDirectoryProto.internal_static_proto_Race_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return belllap.proto.RaceDirectoryProto.internal_static_proto_Race_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                belllap.proto.RaceDirectoryProto.Race.class, belllap.proto.RaceDirectoryProto.Race.Builder.class);
      }

      // Construct using belllap.proto.RaceDirectoryProto.Race.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        date_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        city_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        state_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        raceType_ = belllap.proto.RaceDirectoryProto.Race.RaceType.CRITERIUM;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return belllap.proto.RaceDirectoryProto.internal_static_proto_Race_descriptor;
      }

      public belllap.proto.RaceDirectoryProto.Race getDefaultInstanceForType() {
        return belllap.proto.RaceDirectoryProto.Race.getDefaultInstance();
      }

      public belllap.proto.RaceDirectoryProto.Race build() {
        belllap.proto.RaceDirectoryProto.Race result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public belllap.proto.RaceDirectoryProto.Race buildPartial() {
        belllap.proto.RaceDirectoryProto.Race result = new belllap.proto.RaceDirectoryProto.Race(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.date_ = date_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.city_ = city_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.state_ = state_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.raceType_ = raceType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof belllap.proto.RaceDirectoryProto.Race) {
          return mergeFrom((belllap.proto.RaceDirectoryProto.Race)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(belllap.proto.RaceDirectoryProto.Race other) {
        if (other == belllap.proto.RaceDirectoryProto.Race.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasDate()) {
          setDate(other.getDate());
        }
        if (other.hasCity()) {
          bitField0_ |= 0x00000008;
          city_ = other.city_;
          onChanged();
        }
        if (other.hasState()) {
          bitField0_ |= 0x00000010;
          state_ = other.state_;
          onChanged();
        }
        if (other.hasRaceType()) {
          setRaceType(other.getRaceType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasName()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        belllap.proto.RaceDirectoryProto.Race parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (belllap.proto.RaceDirectoryProto.Race) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>required string id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            id_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      private long date_ ;
      /**
       * <code>optional int64 date = 3;</code>
       */
      public boolean hasDate() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 date = 3;</code>
       */
      public long getDate() {
        return date_;
      }
      /**
       * <code>optional int64 date = 3;</code>
       */
      public Builder setDate(long value) {
        bitField0_ |= 0x00000004;
        date_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 date = 3;</code>
       */
      public Builder clearDate() {
        bitField0_ = (bitField0_ & ~0x00000004);
        date_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object city_ = "";
      /**
       * <code>optional string city = 4;</code>
       */
      public boolean hasCity() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string city = 4;</code>
       */
      public java.lang.String getCity() {
        java.lang.Object ref = city_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            city_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string city = 4;</code>
       */
      public com.google.protobuf.ByteString
          getCityBytes() {
        java.lang.Object ref = city_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          city_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string city = 4;</code>
       */
      public Builder setCity(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        city_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string city = 4;</code>
       */
      public Builder clearCity() {
        bitField0_ = (bitField0_ & ~0x00000008);
        city_ = getDefaultInstance().getCity();
        onChanged();
        return this;
      }
      /**
       * <code>optional string city = 4;</code>
       */
      public Builder setCityBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        city_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object state_ = "";
      /**
       * <code>optional string state = 5;</code>
       */
      public boolean hasState() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string state = 5;</code>
       */
      public java.lang.String getState() {
        java.lang.Object ref = state_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            state_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string state = 5;</code>
       */
      public com.google.protobuf.ByteString
          getStateBytes() {
        java.lang.Object ref = state_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          state_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string state = 5;</code>
       */
      public Builder setState(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string state = 5;</code>
       */
      public Builder clearState() {
        bitField0_ = (bitField0_ & ~0x00000010);
        state_ = getDefaultInstance().getState();
        onChanged();
        return this;
      }
      /**
       * <code>optional string state = 5;</code>
       */
      public Builder setStateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        state_ = value;
        onChanged();
        return this;
      }

      private belllap.proto.RaceDirectoryProto.Race.RaceType raceType_ = belllap.proto.RaceDirectoryProto.Race.RaceType.CRITERIUM;
      /**
       * <code>optional .proto.Race.RaceType raceType = 6;</code>
       */
      public boolean hasRaceType() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional .proto.Race.RaceType raceType = 6;</code>
       */
      public belllap.proto.RaceDirectoryProto.Race.RaceType getRaceType() {
        return raceType_;
      }
      /**
       * <code>optional .proto.Race.RaceType raceType = 6;</code>
       */
      public Builder setRaceType(belllap.proto.RaceDirectoryProto.Race.RaceType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000020;
        raceType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .proto.Race.RaceType raceType = 6;</code>
       */
      public Builder clearRaceType() {
        bitField0_ = (bitField0_ & ~0x00000020);
        raceType_ = belllap.proto.RaceDirectoryProto.Race.RaceType.CRITERIUM;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:proto.Race)
    }

    static {
      defaultInstance = new Race(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.Race)
  }

  public interface RaceDirectoryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.RaceDirectory)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .proto.Race race = 1;</code>
     */
    java.util.List<belllap.proto.RaceDirectoryProto.Race> 
        getRaceList();
    /**
     * <code>repeated .proto.Race race = 1;</code>
     */
    belllap.proto.RaceDirectoryProto.Race getRace(int index);
    /**
     * <code>repeated .proto.Race race = 1;</code>
     */
    int getRaceCount();
    /**
     * <code>repeated .proto.Race race = 1;</code>
     */
    java.util.List<? extends belllap.proto.RaceDirectoryProto.RaceOrBuilder> 
        getRaceOrBuilderList();
    /**
     * <code>repeated .proto.Race race = 1;</code>
     */
    belllap.proto.RaceDirectoryProto.RaceOrBuilder getRaceOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code proto.RaceDirectory}
   */
  public static final class RaceDirectory extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:proto.RaceDirectory)
      RaceDirectoryOrBuilder {
    // Use RaceDirectory.newBuilder() to construct.
    private RaceDirectory(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RaceDirectory(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RaceDirectory defaultInstance;
    public static RaceDirectory getDefaultInstance() {
      return defaultInstance;
    }

    public RaceDirectory getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RaceDirectory(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                race_ = new java.util.ArrayList<belllap.proto.RaceDirectoryProto.Race>();
                mutable_bitField0_ |= 0x00000001;
              }
              race_.add(input.readMessage(belllap.proto.RaceDirectoryProto.Race.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          race_ = java.util.Collections.unmodifiableList(race_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return belllap.proto.RaceDirectoryProto.internal_static_proto_RaceDirectory_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return belllap.proto.RaceDirectoryProto.internal_static_proto_RaceDirectory_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              belllap.proto.RaceDirectoryProto.RaceDirectory.class, belllap.proto.RaceDirectoryProto.RaceDirectory.Builder.class);
    }

    public static com.google.protobuf.Parser<RaceDirectory> PARSER =
        new com.google.protobuf.AbstractParser<RaceDirectory>() {
      public RaceDirectory parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RaceDirectory(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RaceDirectory> getParserForType() {
      return PARSER;
    }

    public static final int RACE_FIELD_NUMBER = 1;
    private java.util.List<belllap.proto.RaceDirectoryProto.Race> race_;
    /**
     * <code>repeated .proto.Race race = 1;</code>
     */
    public java.util.List<belllap.proto.RaceDirectoryProto.Race> getRaceList() {
      return race_;
    }
    /**
     * <code>repeated .proto.Race race = 1;</code>
     */
    public java.util.List<? extends belllap.proto.RaceDirectoryProto.RaceOrBuilder> 
        getRaceOrBuilderList() {
      return race_;
    }
    /**
     * <code>repeated .proto.Race race = 1;</code>
     */
    public int getRaceCount() {
      return race_.size();
    }
    /**
     * <code>repeated .proto.Race race = 1;</code>
     */
    public belllap.proto.RaceDirectoryProto.Race getRace(int index) {
      return race_.get(index);
    }
    /**
     * <code>repeated .proto.Race race = 1;</code>
     */
    public belllap.proto.RaceDirectoryProto.RaceOrBuilder getRaceOrBuilder(
        int index) {
      return race_.get(index);
    }

    private void initFields() {
      race_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getRaceCount(); i++) {
        if (!getRace(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < race_.size(); i++) {
        output.writeMessage(1, race_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < race_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, race_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static belllap.proto.RaceDirectoryProto.RaceDirectory parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static belllap.proto.RaceDirectoryProto.RaceDirectory parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static belllap.proto.RaceDirectoryProto.RaceDirectory parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static belllap.proto.RaceDirectoryProto.RaceDirectory parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static belllap.proto.RaceDirectoryProto.RaceDirectory parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static belllap.proto.RaceDirectoryProto.RaceDirectory parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static belllap.proto.RaceDirectoryProto.RaceDirectory parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static belllap.proto.RaceDirectoryProto.RaceDirectory parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static belllap.proto.RaceDirectoryProto.RaceDirectory parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static belllap.proto.RaceDirectoryProto.RaceDirectory parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(belllap.proto.RaceDirectoryProto.RaceDirectory prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.RaceDirectory}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.RaceDirectory)
        belllap.proto.RaceDirectoryProto.RaceDirectoryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return belllap.proto.RaceDirectoryProto.internal_static_proto_RaceDirectory_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return belllap.proto.RaceDirectoryProto.internal_static_proto_RaceDirectory_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                belllap.proto.RaceDirectoryProto.RaceDirectory.class, belllap.proto.RaceDirectoryProto.RaceDirectory.Builder.class);
      }

      // Construct using belllap.proto.RaceDirectoryProto.RaceDirectory.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRaceFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (raceBuilder_ == null) {
          race_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          raceBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return belllap.proto.RaceDirectoryProto.internal_static_proto_RaceDirectory_descriptor;
      }

      public belllap.proto.RaceDirectoryProto.RaceDirectory getDefaultInstanceForType() {
        return belllap.proto.RaceDirectoryProto.RaceDirectory.getDefaultInstance();
      }

      public belllap.proto.RaceDirectoryProto.RaceDirectory build() {
        belllap.proto.RaceDirectoryProto.RaceDirectory result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public belllap.proto.RaceDirectoryProto.RaceDirectory buildPartial() {
        belllap.proto.RaceDirectoryProto.RaceDirectory result = new belllap.proto.RaceDirectoryProto.RaceDirectory(this);
        int from_bitField0_ = bitField0_;
        if (raceBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            race_ = java.util.Collections.unmodifiableList(race_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.race_ = race_;
        } else {
          result.race_ = raceBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof belllap.proto.RaceDirectoryProto.RaceDirectory) {
          return mergeFrom((belllap.proto.RaceDirectoryProto.RaceDirectory)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(belllap.proto.RaceDirectoryProto.RaceDirectory other) {
        if (other == belllap.proto.RaceDirectoryProto.RaceDirectory.getDefaultInstance()) return this;
        if (raceBuilder_ == null) {
          if (!other.race_.isEmpty()) {
            if (race_.isEmpty()) {
              race_ = other.race_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureRaceIsMutable();
              race_.addAll(other.race_);
            }
            onChanged();
          }
        } else {
          if (!other.race_.isEmpty()) {
            if (raceBuilder_.isEmpty()) {
              raceBuilder_.dispose();
              raceBuilder_ = null;
              race_ = other.race_;
              bitField0_ = (bitField0_ & ~0x00000001);
              raceBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getRaceFieldBuilder() : null;
            } else {
              raceBuilder_.addAllMessages(other.race_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getRaceCount(); i++) {
          if (!getRace(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        belllap.proto.RaceDirectoryProto.RaceDirectory parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (belllap.proto.RaceDirectoryProto.RaceDirectory) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<belllap.proto.RaceDirectoryProto.Race> race_ =
        java.util.Collections.emptyList();
      private void ensureRaceIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          race_ = new java.util.ArrayList<belllap.proto.RaceDirectoryProto.Race>(race_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          belllap.proto.RaceDirectoryProto.Race, belllap.proto.RaceDirectoryProto.Race.Builder, belllap.proto.RaceDirectoryProto.RaceOrBuilder> raceBuilder_;

      /**
       * <code>repeated .proto.Race race = 1;</code>
       */
      public java.util.List<belllap.proto.RaceDirectoryProto.Race> getRaceList() {
        if (raceBuilder_ == null) {
          return java.util.Collections.unmodifiableList(race_);
        } else {
          return raceBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .proto.Race race = 1;</code>
       */
      public int getRaceCount() {
        if (raceBuilder_ == null) {
          return race_.size();
        } else {
          return raceBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .proto.Race race = 1;</code>
       */
      public belllap.proto.RaceDirectoryProto.Race getRace(int index) {
        if (raceBuilder_ == null) {
          return race_.get(index);
        } else {
          return raceBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .proto.Race race = 1;</code>
       */
      public Builder setRace(
          int index, belllap.proto.RaceDirectoryProto.Race value) {
        if (raceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRaceIsMutable();
          race_.set(index, value);
          onChanged();
        } else {
          raceBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Race race = 1;</code>
       */
      public Builder setRace(
          int index, belllap.proto.RaceDirectoryProto.Race.Builder builderForValue) {
        if (raceBuilder_ == null) {
          ensureRaceIsMutable();
          race_.set(index, builderForValue.build());
          onChanged();
        } else {
          raceBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.Race race = 1;</code>
       */
      public Builder addRace(belllap.proto.RaceDirectoryProto.Race value) {
        if (raceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRaceIsMutable();
          race_.add(value);
          onChanged();
        } else {
          raceBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Race race = 1;</code>
       */
      public Builder addRace(
          int index, belllap.proto.RaceDirectoryProto.Race value) {
        if (raceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRaceIsMutable();
          race_.add(index, value);
          onChanged();
        } else {
          raceBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Race race = 1;</code>
       */
      public Builder addRace(
          belllap.proto.RaceDirectoryProto.Race.Builder builderForValue) {
        if (raceBuilder_ == null) {
          ensureRaceIsMutable();
          race_.add(builderForValue.build());
          onChanged();
        } else {
          raceBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.Race race = 1;</code>
       */
      public Builder addRace(
          int index, belllap.proto.RaceDirectoryProto.Race.Builder builderForValue) {
        if (raceBuilder_ == null) {
          ensureRaceIsMutable();
          race_.add(index, builderForValue.build());
          onChanged();
        } else {
          raceBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.Race race = 1;</code>
       */
      public Builder addAllRace(
          java.lang.Iterable<? extends belllap.proto.RaceDirectoryProto.Race> values) {
        if (raceBuilder_ == null) {
          ensureRaceIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, race_);
          onChanged();
        } else {
          raceBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Race race = 1;</code>
       */
      public Builder clearRace() {
        if (raceBuilder_ == null) {
          race_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          raceBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .proto.Race race = 1;</code>
       */
      public Builder removeRace(int index) {
        if (raceBuilder_ == null) {
          ensureRaceIsMutable();
          race_.remove(index);
          onChanged();
        } else {
          raceBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Race race = 1;</code>
       */
      public belllap.proto.RaceDirectoryProto.Race.Builder getRaceBuilder(
          int index) {
        return getRaceFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .proto.Race race = 1;</code>
       */
      public belllap.proto.RaceDirectoryProto.RaceOrBuilder getRaceOrBuilder(
          int index) {
        if (raceBuilder_ == null) {
          return race_.get(index);  } else {
          return raceBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .proto.Race race = 1;</code>
       */
      public java.util.List<? extends belllap.proto.RaceDirectoryProto.RaceOrBuilder> 
           getRaceOrBuilderList() {
        if (raceBuilder_ != null) {
          return raceBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(race_);
        }
      }
      /**
       * <code>repeated .proto.Race race = 1;</code>
       */
      public belllap.proto.RaceDirectoryProto.Race.Builder addRaceBuilder() {
        return getRaceFieldBuilder().addBuilder(
            belllap.proto.RaceDirectoryProto.Race.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.Race race = 1;</code>
       */
      public belllap.proto.RaceDirectoryProto.Race.Builder addRaceBuilder(
          int index) {
        return getRaceFieldBuilder().addBuilder(
            index, belllap.proto.RaceDirectoryProto.Race.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.Race race = 1;</code>
       */
      public java.util.List<belllap.proto.RaceDirectoryProto.Race.Builder> 
           getRaceBuilderList() {
        return getRaceFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          belllap.proto.RaceDirectoryProto.Race, belllap.proto.RaceDirectoryProto.Race.Builder, belllap.proto.RaceDirectoryProto.RaceOrBuilder> 
          getRaceFieldBuilder() {
        if (raceBuilder_ == null) {
          raceBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              belllap.proto.RaceDirectoryProto.Race, belllap.proto.RaceDirectoryProto.Race.Builder, belllap.proto.RaceDirectoryProto.RaceOrBuilder>(
                  race_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          race_ = null;
        }
        return raceBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:proto.RaceDirectory)
    }

    static {
      defaultInstance = new RaceDirectory(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.RaceDirectory)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Race_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_Race_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_RaceDirectory_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_RaceDirectory_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023racedirectory.proto\022\005proto\"\310\001\n\004Race\022\n\n" +
      "\002id\030\001 \002(\t\022\014\n\004name\030\002 \002(\t\022\014\n\004date\030\003 \001(\003\022\014\n" +
      "\004city\030\004 \001(\t\022\r\n\005state\030\005 \001(\t\022&\n\010raceType\030\006" +
      " \001(\0162\024.proto.Race.RaceType\"S\n\010RaceType\022\r" +
      "\n\tCRITERIUM\020\000\022\r\n\tROAD_RACE\020\001\022\016\n\nHILL_CLI" +
      "MB\020\002\022\016\n\nTIME_TRIAL\020\003\022\t\n\005OTHER\020\004\"*\n\rRaceD" +
      "irectory\022\031\n\004race\030\001 \003(\0132\013.proto.RaceB#\n\rb" +
      "elllap.protoB\022RaceDirectoryProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_Race_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_Race_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_Race_descriptor,
        new java.lang.String[] { "Id", "Name", "Date", "City", "State", "RaceType", });
    internal_static_proto_RaceDirectory_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_RaceDirectory_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_RaceDirectory_descriptor,
        new java.lang.String[] { "Race", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
